
name: Abhishek Chandrasekar
title: Abhishek Chandrasekar
description: "My portfolio of things I'm interested in and potentially a place for future blogs tech related."
url: https://achandrasekar.com
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
